name: user_repository
description: handle user authentication
version: 0.0.1

environment:
  sdk: '>=3.2.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.1
  cloud_firestore: ^4.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
